version: '2'

services:

   query:
     container_name: query
     image: books.query:latest
     expose:
       - 8080
     restart: always
     logging:
       driver: "json-file"
     networks:
       - booknet
     environment:
       # GOOGLE_API_KEY must be set in .env file
       - googleapikey=${GOOGLE_API_KEY}

   swagger:
    container_name: swagger
    image: hipposareevil/swagger-combine
    restart: always
    logging:
      driver: "json-file"
    expose:
      - 8080
    networks:
      - booknet
    environment:
    # combine_urls: comma separated list of URLs to gather yaml entries
      - COMBINE_URLS=author:8080/swagger.yaml,title:8080/swagger.yaml,query:8080/v2/api-docs,frontend:80/swagger.yaml

   booksdb:
    container_name: booksdb
    image: mysql:latest
    volumes:
      - "./mysql/books.sql:/docker-entrypoint-initdb.d/books.sql"
    restart: always
    logging:
      driver: "json-file"
    networks:
      - booknet
    environment:
     - MYSQL_ROOT_PASSWORD=booksit 
     - MYSQL_DATABASE=booksdatabase
     - MYSQL_USER=booksuser 
     - MYSQL_PASSWORD=books 


   author:
     container_name: author
     image: books.author:latest
     ports:
       - 9999:8080
     expose:
       - 8080
     restart: always
     logging:
       driver: "json-file"
     networks:
       - booknet

   title:
     container_name: title
     image: books.title:latest
     expose:
       - 8080
     restart: always
     logging:
       driver: "json-file"
     networks:
       - booknet
  
   # frontend gateway-api runs on port 80 internally
   frontend:
     container_name: frontend
     image: books.nginx:latest
     ports:
       - 8080:80 
     restart: always
     logging:
       driver: "json-file"
     depends_on:
      - author
     networks:
      - booknet


networks:
   booknet:
