version: '3.2'

services:
   # Graphite metrics collector
   graphite:
     container_name: graphite
     image: graphiteapp/graphite-statsd:latest
     restart: always
     ports:
      - 3001:80
     logging:
       driver: "json-file"
     volumes:
      - "./graphite/conf/:/opt/graphite/conf/"
      - "./graphite/storage/:/opt/graphite/storage/"

   # Grafana UI for viewing graphite data
   grafana:
     container_name: grafana
     image: grafana/grafana:latest
     ports:
      - 3000:3000
     restart: always
     logging:
       driver: "json-file"
     volumes:
      - "./grafana/:/var/lib/grafana"

networks:
  default:
    external:
      name: books_booknet
